name: CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Output Run ID
        run: echo ${{ github.run_id }}

      - name: Output Run Number
        run: echo ${{ github.run_number }}

      - uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 6.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore

      # - name: Pack NuGet package
      #   # if: github.ref == 'refs/heads/master'
      #   run: dotnet pack -o .

      # - name: Publish NuGet package
      #   shell: bash
      #   # if: github.ref == 'refs/heads/master'
      #   env:
      #     NUGET_KEY: ${{secrets.NUGET_KEY}}
      #   run: dotnet nuget push "*.nupkg" -k "$NUGET_KEY" -s https://api.nuget.org/v3/index.json
    

